const avatar = (seed) =>
  `https://api.dicebear.com/9.x/lorelei/svg?seed=${encodeURIComponent(seed)}`;

export const EVENTS = [
  {
    id: 1,
    name: 'Angular Signals in Action',
    city: 'lima',
    category: 'frontend',
    modality: 'presencial',
    date: '12 oct 2026',
    venue: 'Hub Innovación Miraflores',
    summary:
      'Taller práctico intensivo para construir interfaces reactivas de altísimo rendimiento con Angular 22, computeds y state primitives.',
    speaker: { name: 'Elena Ramos', role: 'GDE in Angular', avatar: avatar('Elena Ramos') },
    seats: 12,
    popular: true,
    free: false,
  },
  {
    id: 2,
    name: 'Angular Reactive Data Lab',
    city: 'lima',
    category: 'frontend',
    modality: 'online',
    date: '18 oct 2026',
    venue: 'Sala virtual Andes',
    summary:
      'Laboratorio en vivo para explorar patrones reactivos de streaming, WebSockets y gestión de catálogos en tiempo real.',
    speaker: { name: 'Carlos Vega', role: 'Tech Lead @ Pulse', avatar: avatar('Carlos Vega') },
    seats: 48,
    popular: true,
    free: true,
  },
  {
    id: 3,
    name: 'Angular SSR Workshop',
    city: 'bogota',
    category: 'frontend',
    modality: 'hibrido',
    date: '24 oct 2026',
    venue: 'Campus Chapinero',
    summary:
      'Renderizado del lado del servidor de alto desempeño, SEO técnico y estrategias de hidratación parcial en Angular 22.',
    speaker: { name: 'Mateo Restrepo', role: 'Principal Architect', avatar: avatar('Mateo Restrepo') },
    seats: 28,
    popular: false,
    free: false,
  },
  {
    id: 4,
    name: 'Modern Angular Architecture',
    city: 'santiago',
    category: 'frontend',
    modality: 'presencial',
    date: '30 oct 2026',
    venue: 'Centro Parque',
    summary:
      'Diseño por dominios, standalone component patterns y optimización de estado local para monorepos empresariales.',
    speaker: { name: 'Francisca Silva', role: 'Enterprise Consultant', avatar: avatar('Francisca Silva') },
    seats: 5,
    popular: false,
    free: false,
  },
  {
    id: 5,
    name: 'NestJS API Foundations',
    city: 'lima',
    category: 'backend',
    modality: 'presencial',
    date: '5 nov 2026',
    venue: 'Laboratorio San Isidro',
    summary:
      'Diseño de APIs escalables y tipadas con NestJS, inyección de dependencias avanzada y contratos de prueba robustos.',
    speaker: { name: 'Diego Paredes', role: 'Staff Engineer', avatar: avatar('Diego Paredes') },
    seats: 18,
    popular: true,
    free: false,
  },
  {
    id: 6,
    name: 'Node Performance Clinic',
    city: 'bogota',
    category: 'backend',
    modality: 'online',
    date: '8 nov 2026',
    venue: 'Sala virtual Sabana',
    summary:
      'Diagnóstico de cuellos de botella en el event loop, fugas de memoria y benchmarks de latencia p99 en Node 22.',
    speaker: { name: 'Andrés Morales', role: 'SRE Specialist', avatar: avatar('Andres Morales') },
    seats: 60,
    popular: false,
    free: true,
  },
  {
    id: 7,
    name: 'Event-Driven Backend',
    city: 'santiago',
    category: 'backend',
    modality: 'hibrido',
    date: '14 nov 2026',
    venue: 'Nodo Providencia',
    summary: 'Mensajería, idempotencia y flujos asíncronos en producción.',
    speaker: { name: 'Camila Herrera', role: 'Platform Engineer', avatar: avatar('Camila Herrera') },
    seats: 16,
    popular: false,
    free: false,
  },
  {
    id: 8,
    name: 'GraphQL for Backend Teams',
    city: 'lima',
    category: 'backend',
    modality: 'online',
    date: '19 nov 2026',
    venue: 'Sala virtual Pacífico',
    summary: 'Esquemas, consultas y límites prácticos de un grafo de datos.',
    speaker: { name: 'Rodrigo Salazar', role: 'API Designer', avatar: avatar('Rodrigo Salazar') },
    seats: 22,
    popular: false,
    free: false,
  },
  {
    id: 9,
    name: 'AWS Cloud Architect Day',
    city: 'lima',
    category: 'cloud',
    modality: 'presencial',
    date: '22 nov 2026',
    venue: 'Torre Javier Prado',
    summary: 'Arquitecturas cloud compactas para APIs y frontends.',
    speaker: { name: 'Valeria Quispe', role: 'Cloud Architect', avatar: avatar('Valeria Quispe') },
    seats: 15,
    popular: true,
    free: false,
  },
  {
    id: 10,
    name: 'Kubernetes Hands-on',
    city: 'bogota',
    category: 'cloud',
    modality: 'online',
    date: '26 nov 2026',
    venue: 'Sala virtual Cordillera',
    summary: 'Pods, servicios y despliegues sin complejidad innecesaria.',
    speaker: { name: 'Nicolás Duarte', role: 'DevOps Engineer', avatar: avatar('Nicolas Duarte') },
    seats: 40,
    popular: false,
    free: true,
  },
  {
    id: 11,
    name: 'Terraform Workshop',
    city: 'santiago',
    category: 'cloud',
    modality: 'hibrido',
    date: '2 dic 2026',
    venue: 'Espacio Lastarria',
    summary: 'Infraestructura como código para entornos de desarrollo y taller.',
    speaker: { name: 'Javiera Rojas', role: 'Infra Engineer', avatar: avatar('Javiera Rojas') },
    seats: 9,
    popular: false,
    free: false,
  },
  {
    id: 12,
    name: 'Multi-cloud Observability',
    city: 'lima',
    category: 'cloud',
    modality: 'online',
    date: '6 dic 2026',
    venue: 'Sala virtual Costa',
    summary: 'Logs, métricas y trazas para detectar fallos de red.',
    speaker: { name: 'Martín Castillo', role: 'SRE', avatar: avatar('Martin Castillo') },
    seats: 30,
    popular: false,
    free: false,
  },
  {
    id: 13,
    name: 'Applied AI with Gemini',
    city: 'lima',
    category: 'ai',
    modality: 'presencial',
    date: '9 dic 2026',
    venue: 'Laboratorio Pueblo Libre',
    summary: 'Casos de uso de IA aplicados a productos web.',
    speaker: { name: 'Lucía Mendoza', role: 'AI Engineer', avatar: avatar('Lucia Mendoza') },
    seats: 8,
    popular: true,
    free: false,
  },
  {
    id: 14,
    name: 'LLM Engineering Lab',
    city: 'bogota',
    category: 'ai',
    modality: 'online',
    date: '12 dic 2026',
    venue: 'Sala virtual Magdalena',
    summary: 'Prompts, evaluación y límites de los modelos generativos.',
    speaker: { name: 'Sofía Aguilar', role: 'ML Engineer', avatar: avatar('Sofia Aguilar') },
    seats: 36,
    popular: false,
    free: true,
  },
  {
    id: 15,
    name: 'Responsible AI Forum',
    city: 'santiago',
    category: 'ai',
    modality: 'hibrido',
    date: '16 dic 2026',
    venue: 'Centro Cultural Estación',
    summary: 'Riesgos, sesgos y criterios de publicación de sistemas IA.',
    speaker: { name: 'Pablo Núñez', role: 'Ethics Lead', avatar: avatar('Pablo Nunez') },
    seats: 24,
    popular: false,
    free: false,
  },
  {
    id: 16,
    name: 'AI Agents in Production',
    city: 'lima',
    category: 'ai',
    modality: 'online',
    date: '18 dic 2026',
    venue: 'Sala virtual Inca',
    summary: 'Orquestación de agentes con herramientas y supervisión humana.',
    speaker: { name: 'Renata Flores', role: 'Applied Scientist', avatar: avatar('Renata Flores') },
    seats: 6,
    popular: true,
    free: false,
  },
  {
    id: 17,
    name: 'From React to Angular',
    city: 'bogota',
    category: 'frontend',
    modality: 'presencial',
    date: '21 dic 2026',
    venue: 'Casa de la Carrera',
    summary: 'Correspondencias entre componentes, estado e inputs al migrar.',
    speaker: { name: 'Juan Pablo Ortiz', role: 'Frontend Lead', avatar: avatar('Juan Pablo Ortiz') },
    seats: 14,
    popular: false,
    free: false,
  },
  {
    id: 18,
    name: 'Cloud Native Backend',
    city: 'santiago',
    category: 'backend',
    modality: 'presencial',
    date: '28 dic 2026',
    venue: 'Nodo Las Condes',
    summary: 'Servicios pequeños y contratos claros para backends nativos cloud.',
    speaker: { name: 'Tomás Vidal', role: 'Backend Lead', avatar: avatar('Tomas Vidal') },
    seats: 11,
    popular: false,
    free: false,
  },
];
